Image proxy
yuszafar/blog-CRUD-eldor pull request #7
Opened 2020-11-19 11:10 UTC by electrofocus

2020-11-19 16:38 UTC, DilsMatchanov requested changes

2020-11-19 16:38 UTC, DilsMatchanov commented on api/v1/image/serializers.py
> +        img = Im.open(BytesIO(response.content))
при загрузке изображения нужно сохранять его оригинальное разрешение. А обрезка должна происходить уже по эндпоинту.

Например:
`/imageproxy/200/<image_url>` <- получить изображение с шириной 200 пикселей с сохранением соотношения сторон.

2020-11-19 16:38 UTC, DilsMatchanov commented on api/v1/image/serializers.py
> +        img = Im.open(BytesIO(response.content))
и вообще думаю можно обойтись без загрузки самого изображения так как это не функционал image proxy и, все равно, на вход можно подать любой url

2020-11-19 16:38 UTC, DilsMatchanov commented on api/v1/image/serializers.py
> +        img = Im.open(BytesIO(response.content))
+ плохая практика писать функционал самой обрезки в сериалайзере. Было бы лучше вынести всю логику для работы с изображениями в отдельный модуль

2020-11-20 07:55 UTC, DilsMatchanov approved these changes
LGTM!

2020-11-21 09:08 UTC, electrofocus commented
Fixed #5

2020-11-21 09:45 UTC, yuszafar approved these changes
LGTM

2020-11-21 09:45 UTC, merged